#!/bin/bash

# http://stackoverflow.com/questions/14170590/building-qt-5-on-linux-for-windows

# cd /opt
# sudo mkdir mxe
# sudo chown $USER mxe
# git clone https://github.com/mxe/mxe.git
# sudo apt-get install autoconf automake autopoint bash bison bzip2 flex gettext git g++ gperf intltool libffi-dev libgdk-pixbuf2.0-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils g++-multilib libc6-dev-i386 libtool-bin
# cd mxe
# make qtbase
# make qtserialport
# make qtconnectivity
# make qtquickcontrols
# make qtquickcontrols2

export PATH=~/mxe/usr/bin/:$PATH
rm -rf build/win/*

# Original
~/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -config release "CONFIG+=release_win build_original"
make clean
make -j8
rm -rf build/win/obj
cd build/win
mv FOCBOX_UI*.exe FOCBOX_TOOL.exe
zip FOCBOX_TOOL.zip FOCBOX_TOOL.exe
ls | grep -v '\.zip$' | xargs rm
cd ../..

# Platinum
~/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -config release "CONFIG+=release_win build_original build_mobile"
make clean
make -j8
rm -rf build/win/obj
cd build/win
zip FOCBOX_UI.zip FOCBOX_UI*.exe
ls | grep -v '\.zip$' | xargs rm
cd ../..

